# Generated by Django 5.1.7 on 2025-06-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_saileddata_createdat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Port', models.CharField(default='', max_length=40, unique=True)),
                ('UpdateAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
