# Generated by Django 5.1.7 on 2025-06-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_portsupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortsUpdate',
        ),
        migrations.AddField(
            model_name='port_berth_form',
            name='PIC1Mail',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='port_berth_form',
            name='PIC2Mail',
            field=models.EmailField(default='', max_length=30),
        ),
    ]
