# Generated by Django 5.1.7 on 2025-06-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_delete_portsupdate_port_berth_form_pic1mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniquePortDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(default='', max_length=20)),
                ('Port', models.CharField(default='', max_length=20, unique=True)),
                ('PIC1Mail', models.EmailField(default='', max_length=30)),
                ('PIC2Mail', models.EmailField(default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Unique Port Detail',
                'verbose_name_plural': 'Unique Port Details',
            },
        ),
        migrations.AlterModelOptions(
            name='port_berth_form',
            options={'verbose_name': 'Port Berth Form', 'verbose_name_plural': 'Port Berth Forms'},
        ),
    ]
