# Generated by Django 5.1.7 on 2025-06-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_uniqueportdetails_alter_port_berth_form_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='port_berth_form',
            name='PIC3Mail',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='uniqueportdetails',
            name='PIC3Mail',
            field=models.EmailField(default='', max_length=30),
        ),
    ]
