# Generated by Django 5.1.7 on 2025-06-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_port_berth_form_pic3mail_uniqueportdetails_pic3mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueportdetails',
            name='LastUpdated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
