# Generated by Django 5.1.7 on 2025-06-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_uniqueportdetails_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueportdetails',
            name='LastUpdated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
